name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.ref_name }}
      CERT_ARN: ${{ secrets.CERT_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install


      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          bun pm trust --all
          bun run deploy
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "18.x"

      # - name: Get npm cache directory
      #   id: npm-cache-dir
      #   shell: bash
      #   run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      # - uses: actions/cache@v4
      #   id: npm-cache
      #   with:
      #     path: ${{ steps.npm-cache-dir.outputs.dir }}
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # - name: Deploy
      #   if: ${{ github.ref == 'refs/heads/master' }}
      #   # Run the deploy command with environment variables
      #   run: |
      #     npm install --no-audit && npx sst deploy --stage prod
